#!/bin/bash
#
# WIP: Currently thinkpad-rotate cannot be started this way!
#
### BEGIN INIT INFO
# Provides: thinkpad-rotated
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Test daemon process
# Description:    Runs up the ThinkPad Rotate daemon process
### END INIT INFO

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    /usr/bin/thinkpad-rotate start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    /usr/bin/thinkpad-rotate stop
    ;;
  restart)
    echo "Restarting server"
    /usr/bin/thinkpad-rotate restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/thinkpad-rotated {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
