#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

toggle() {
	xinput set-prop "$1" "Device Enabled" "$2"
	echo "Toggling input device $1 to $2."
}

# Find the ID of the TouchPad.
id="$(xinput list | grep TouchPad | grep --only-matching -P 'id=(\d+)' | cut -c 4-)"

# Check whether this device is disabled.
if xinput --list "$id" | grep -i disabled
then
	toggle "$id" 1
else
	toggle "$id" 0
fi
