#!/bin/bash
# Copyright © 2012 Jim Turner <jturner314@gmail.com>
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.

### BEGIN INIT INFO
# Default-Start: 2 3 4 5
# Short-Description: Sets keycodes for ThinkPad X220
### END INIT INFO

setkeycodes 6e 109 6d 104 69 28 6b 01 6c 120
