#!/bin/bash
# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

set -e
set -u

internal="LVDS1"
external="HDMI2"

if [[ -z "${1:-}" ]]
then
	echo "usage: think-dock on|off"
	echo "See “man think-dock” for more details."
	exit 2
fi

case "$1" in
	on)
		xrandr --output "$internal" --mode 1366x768
		xrandr --output "$external" --mode 1920x1200 --right-of "$internal" --primary
		;;
	off)
		xrandr --output "$internal" --mode 1366x768 --primary
		xrandr --output "$external" --off
		;;
esac

for device in "Wacom ISDv4 E6 Pen stylus" "Wacom ISDv4 E6 Finger touch" "Wacom ISDv4 E6 Pen eraser"
do
	xsetwacom set "$device" MapToOutput "$internal"
done
