#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

case "$1" in
  abort-upgrade|abort-remove|abort-deconfigure|configure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

udevadm hwdb --update

modprobe thinkpad_acpi
modprobe tp_smapi
modprobe hdaps
modprobe acpi_call

if which systemctl &> /dev/null; then
    systemctl restart acpid;
    systemctl daemon-reload;
    #systemctl enable thinkpad-rotated@;
    #systemctl start thinkpad-rotated@$LOGNAME;
elif which service &> /dev/null; then
    service acpid restart;
    #service thinkpad-rotated restart;
fi

#DEBHELPER#
