#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

case "$1" in

  purge|upgrade|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

if which systemctl &> /dev/null; then
  systemctl restart acpid;
elif which service &> /dev/null; then
  service acpid restart;
fi

#DEBHELPER#
