#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

case "$1" in
  abort-upgrade|abort-remove|abort-deconfigure|configure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

udevadm hwdb --update

if which systemctl &> /dev/null; then
    systemctl restart acpid;
elif which service &> /dev/null; then
    service acpid restart;
fi

#DEBHELPER#
